### ISSUE TITLE
Nuget packages are not installed to defined folder

### ISSUE THREAD

**Issue by aun408** [WildGums/Orc.LicenseManager#10]
.NET version: 4.6.1
VS 2017

### Nuget Info
Name             : Package Manager Host
Version          : 4.7.0.5212
InstanceId       : a2efd8da-b588-49c7-adc7-f697425fd76b
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-MY
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

### Expected behaviour
Nuget install pakages in lib folder as defined in NuGet.Config

### Actual behaviour
However when rebuild the project, the nuget packages got installed to $(UserProfile)\.nuget\packages\

**Comment by GeertvanHorrik** [comment]
I think this is because of the new nuget version which always puts the nuget packages into the user profile directory. I think this ticket should be opened in the [NuGet repository](https://github.com/NuGet/Home) instead of this one.

**Comment by aun408** [comment]
However if I created new project or copy out Orc.LicenseManager.Server.Website to run independently, Nuget will install it into package folder at project root.

**Comment by burnignlife** [comment]
Hi!  I can't even restore packages. Other projects in solution works and restore fine.
How can I fix that? Thanks!
![screenshot_1](https://user-images.githubusercontent.com/15861846/45603536-71cb9300-ba35-11e8-9057-b809a382deab.png)
![screenshot_1](https://user-images.githubusercontent.com/15861846/45603580-df77bf00-ba35-11e8-96d7-14e4e163e35b.png)

**Comment by GeertvanHorrik** [comment]
Everything has a new project structure, except for the website (we use a different approach ourselves anyway, it's more of an example). The NuGet.config inside /src should make sure the packages are being restored correctly. Are you sure you are running a recent version of Visual Studio so the packages can be restored correctly?

**Comment by burnignlife** [comment]
VS commutity 2017 ver 15.7.6
I try to copy paste project outside of solution and have the same result.
Is it possible to share  your existing solution? If it doesn't contains specific feaures.
