### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by bsee08** [WildGums/Orc.LicenseManager#2]

**Comment by bsee08** [comment]
Oops. Didn't mean to create the issue empty.

In the sample for the server, it looks like an Admin user is already created, as well as some sample software added. I'm assuming this is to provide a demo of what's possible. 

What's the password for the admin in the example?  If it's posted somewhere, I haven't found it.

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orc.LicenseManager/blob/develop/src/Orc.LicenseManager.Server.Core/Orc.LicenseManager.Server.Core.Shared/Data/RecreateContext.cs#L33
