### ISSUE TITLE
what is the default account for admin login

### ISSUE THREAD

**Issue by li0803** [WildGums/Orc.LicenseManager#3]
hi developers,

What is the default account to login to managing site?

Thanks

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orc.LicenseManager/blob/develop/src/Orc.LicenseManager.Server.Core/Orc.LicenseManager.Server.Core.Shared/Data/RecreateContext.cs#L33

**Comment by li0803** [comment]
thanks
