### ISSUE TITLE
Fody.ModuleInit (used in Client.WPF.Example) has been deprecated in favor of C# 9 built-in module initializers

### ISSUE THREAD

**Issue by skst** [WildGums/Orc.LicenseManager#806]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] Blazor WASM
 - [ ] .NET Core

## Component

What component is this issue occurring in?

Client.WPF.Example

## Version of Library

2.1.1

## Version of OS(s) listed above with issue

Windows 10, 11, ...

## Steps to Reproduce

https://www.nuget.org/packages/ModuleInit.Fody/

"This package has been deprecated as it is legacy and is no longer maintained."

"use https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers"

## Expected Behavior

Use C# 9 module initializers instead.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We are aware but need to migrate all our components at once to solve this "problem". Since it's compile-time only and still working, we consider this low priority until we have resources available to work on this.
