### ISSUE TITLE
LicenseWindow is not shown in my repro

### ISSUE THREAD

**Issue by samirem** [WildGums/Orc.LicenseManager#9]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

Run the repro 
[LicenseRepro.zip](https://github.com/WildGums/Orc.LicenseManager/files/1683372/LicenseRepro.zip)

Platform:
.NET version: 4.6.1

### Expected behaviour

The LicenseWindow should show when running the repro app.

### Actual behaviour

The LicenseWindow is not shown. It is closed right after constructed.

**Comment by GeertvanHorrik** [comment]
The main window of your app is your splash screen, and the license dialog sets the splash screen as parent. But... because the splash gets closed, so does the license dialog.

Simply set this in your MainView.xaml.cs:

```
        public MainView()
        {
            InitializeComponent();

            Application.Current.MainWindow = this;
        }
```
